export const storeProduct = [
    {
        id:1,
        name:"Pink Donut",
        img:"items/item2.jpg",
        price:1000,
        category:"food",
        amount:0
    },
    {
        id:2,
        name:"Brow Donut",
        img:"items/item3.jpg",
        price:1000,
        category:"food",
        amount:0
    },
    {
        id:3,
        name:"Banana",
        img:"items/item4.jpg",
        price:5000,
        category:"food",
        amount:0
    },
    {
        id:4,
        name:"Lemon",
        img:"items/item5.jpg",
        price:1000,
        category:"food",
        amount:0
    },
    {
        id:5,
        name:"Cabbage",
        img:"items/item6.jpg",
        category:"food",
        price:2000,
        amount:0
    },
    {
        id:6,
        name:"Bluey Ice-cream",
        img:"items/ice-cream1.jpg",
        price:3000,
        category:"food",
        amount:0
    },
    {
        id:7,
        name:"Yellow Ice-cream",
        img:"items/ice-cream2.jpg",
        price:1000,
        category:"food",
        amount:0
    },
    {
        id:8,
        name:"Orange Ice-cream",
        img:"items/ice-cream3.jpg",
        price:2000,
        category:"food",
        amount:0
    },
    {
        id:9,
        name:"Red Wine",
        img:"items/drink1.jpg",
        price:2000,
        category:"drink",
        amount:0
    },
    {
        id:10,
        name:"A Beer",
        img:"items/drink2.jpg",
        price:3000,
        category:"drink",
        amount:0
    },
    {
        id:11,
        name:"CocaCola",
        img:"items/drink3.jpg",
        price:4000,
        category:"drink",
        amount:0
    }
]