export const storeProduct = [
    {
        id:1,
        name:"item1",
        img:"/untitled-1.png",
        price:1000,
        category:"drink",
        amount:0
    },
    {
        id:2,
        name:"item2",
        img:"/untitled-1.png",
        price:1000,
        category:"drink",
        amount:0
    },
    {
        id:3,
        name:"item3",
        img:"/untitled-1.png",
        price:1000,
        category:"food",
        amount:0
    },
    {
        id:4,
        name:"item4",
        img:"/untitled-1.png",
        price:1000,
        category:"food",
        amount:0
    },
    {
        id:5,
        name:"item4",
        img:"/untitled-1.png",
        category:"food",
        price:1000,
        amount:0
    },
    {
        id:6,
        name:"item4",
        img:"/untitled-1.png",
        price:1000,
        category:"drink",
        amount:0
    },
    {
        id:7,
        name:"item4",
        img:"/untitled-1.png",
        price:1000,
        category:"drink",
        amount:0
    }
]